apiVersion: v1
kind: Secret
metadata:
  name: community-backend-secret
  namespace: community
type: Opaque
stringData:
  DB_URL: jdbc:mysql://leo-community-db.cp68ecgyk7sn.ap-northeast-2.rds.amazonaws.com:3306/community?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&sslMode=REQUIRED
  DB_USERNAME: community_app
  DB_PASSWORD: ghduswlrl1745!
  JWT_SECRET: XIka85Yam2cMjqtr1doeXnZTeWvGkcOvoHlhxlTUugHarsQVMx8dMwHSAXNrjc02
