apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-backend-deployment
  namespace: community
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: community
      tier: backend

  template:
    metadata:
      labels:
        app: community
        tier: backend
        component: api

    spec:
      terminationGracePeriodSeconds: 40
      containers:
        - name: backend
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          image: 501479502338.dkr.ecr.ap-northeast-2.amazonaws.com/community/backend:git-ed518f1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: community-backend-config
            - secretRef:
                name: community-backend-secret
          resources:
            requests:
              cpu: "150m"
              memory: "640Mi"
            limits:
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 3
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
      