apiVersion: v1
kind: Service
metadata:
  name: community-backend-svc
  namespace: community
  labels:
    app: community
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: community
    tier: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP