loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: s3
    bucketNames:
      chunks: leo-community-loki-logs-501479502338-ap-northeast-2-an
      ruler: leo-community-loki-logs-501479502338-ap-northeast-2-an
      admin: leo-community-loki-logs-501479502338-ap-northeast-2-an
    s3:
      region: ap-northeast-2
  limits_config:
    retention_period: 168h
  compactor:
    retention_enabled: true
    delete_request_store: s3

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  persistence:
    enabled: true
    storageClass: ebs-sc
    size: 5Gi

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

gateway:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false
test:
  enabled: false

chunksCache:
  enabled: false
resultsCache:
  enabled: false
