alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 3d
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        memory: 700Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      memory: 512Mi
  adminPassword: "REPLACE_ME"
  persistence:
    enabled: true
    storageClassName: ebs-sc-retain
    size: 2Gi
  service:
    type: NodePort
  ingress:
    enabled: true
    ingressClassName: alb
    hosts:
      - grafana.leo-community.xyz
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:501479502338:certificate/9de78de7-9ef6-4d88-8969-3ff40c8e3fff
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/group.name: community
      alb.ingress.kubernetes.io/healthcheck-path: /api/health

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
