apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-ingress
  namespace: community
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: community
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
        {{- range .Values.backend.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.backend.serviceName }}
                port:
                  number: {{ $.Values.backend.servicePort }}
        {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.serviceName }}
                port:
                  number: {{ .Values.frontend.servicePort }}
