configs:
  params:
    server.insecure: true

server:
  service:
    type: NodePort
  ingress:
    enabled: true
    ingressClassName: alb
    hostname: argocd.leo-community.xyz
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:501479502338:certificate/9de78de7-9ef6-4d88-8969-3ff40c8e3fff
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/group.name: community
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
