apiVersion: v1
kind: Service
metadata:
  name: community-frontend-svc
  namespace: community
  labels:
    app: community
    tier: frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthcheck.path }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.healthcheckSuccessCodes | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: community
    tier: frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
